import {
  Accordion,
  AccordionItem,
  AccordionButton,
  AccordionPanel,
  Flex,
  useColorModeValue,
  Text,
  Container,
  Heading,
} from '@chakra-ui/react';

import { ChevronDownIcon } from '@chakra-ui/icons';

const FaqsComponent = () => {
  const faqs = [
    {
      question: 'How does this system help me as a patient?',
      answer:
        'Our system allows you to easily request lab tests and book appointments directly from the application, providing a convenient way to manage your health.',
    },
    {
      question: 'Can I track the progress of my lab tests?',
      answer:
        'Yes, you can track the progress of your lab tests using the application. The system ensures transparency and keeps you informed throughout the process.',
    },
    {
      question: 'Is it easy to book appointments through the application?',
      answer:
        'Absolutely! Booking appointments is a breeze with our user-friendly interface. You can schedule appointments with just a few clicks.',
    },
    {
      question: 'What languages are supported for patient interactions?',
      answer:
        'The application supports a variety of languages, ensuring that you can interact with it in a language you are comfortable with.',
    },
    {
      question: 'How quickly can I receive my test results?',
      answer:
        'Our efficient system minimizes processing time, allowing you to receive your test results in a timely manner. Say goodbye to long waiting periods!',
    },
    {
      question: 'Can I send lab test requests from the comfort of my home?',
      answer:
        'Yes, you can conveniently send lab test requests from the comfort of your home through our user-friendly application.',
    },
    {
      question: 'What benefits does the system offer to patients?',
      answer:
        'The system streamlines the lab testing process, making it more efficient and reducing the overall time and effort required from your end.',
    },
    {
      question: 'How secure is my health information within the application?',
      answer:
        'We prioritize the security of your health information. The application employs robust measures to ensure the confidentiality and integrity of your data.',
    },
    {
      question: 'Can I easily understand the reports generated by the system?',
      answer:
        'Absolutely! The system generates reports in a user-friendly format, ensuring that you can easily understand and interpret your health information.',
    },
    {
      question:
        'Is the application accessible for individuals with diverse needs?',
      answer:
        'Yes, the application is designed to be accessible to individuals with diverse needs, providing an inclusive and user-friendly experience.',
    },
  ];

  return (
    <>
      <Heading
        mt="50px"
        align={'center'}
        fontSize={{ base: '2xl', sm: '4xl' }}
        fontWeight={'bold'}
      >
        FAQs
      </Heading>
      <Flex
        minH={'50vh'}
        align={'center'}
        justify={'center'}
        bg={useColorModeValue('gray.50', 'gray.800')}
      >
        <Container>
          <Accordion allowMultiple width="100%" maxW="lg" rounded="lg">
            {faqs.map((faq, index) => (
              <AccordionItem key={index}>
                <AccordionButton
                  display="flex"
                  alignItems="center"
                  justifyContent="space-between"
                  p={4}
                >
                  <Text fontSize="md" color="gray.300">
                    {faq.question}
                  </Text>
                  <ChevronDownIcon fontSize="24px" />
                </AccordionButton>
                <AccordionPanel pb={4}>
                  <Text color="gray.600">{faq.answer}</Text>
                </AccordionPanel>
              </AccordionItem>
            ))}
          </Accordion>
        </Container>
      </Flex>
    </>
  );
};

export default FaqsComponent;
